definitions:
  scripts:
    - &create_env_files
      name: 🔑 Create API Key file
      script: |
        touch .env.prod
        touch .env.dev
        echo "$PROD_SECRET_ANDROID" >> .env.prod
        echo "$PROD_API_HOST" >> .env.prod
        echo "$DEV_SECRET_ANDROID" >> .env.dev
        echo "$DEV_API_HOST" >> .env.dev

    - &set_up_local_properties
      name: 🛠️ Set up local properties
      script: |

        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"

    - &shorebird_install
      name: 📍 Install Shorebird CLI
      script: |

        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        echo PATH="/Users/builder/.shorebird/bin:$PATH" >> $CM_ENV

    - &run_build_runner
      name: 🛠️ Run Build Runner
      script: |

        dart run build_runner build

    - &flutter_analyze
      name: 🔍 Run static code analysis
      script: flutter analyze

    - &use_provisioning_profiles
      name: 🔑 Apply Provisioning Profiles
      script: |
        xcode-project use-profiles

    - &build_android
      name: 🤖 Android Release Build
      script: |
        shorebird release android --flavor ${FLAVOR} --target lib/main_${TARGET}.dart

    - &build_ios
      name: 🍎 iOS Release Build
      script: |
        shorebird release ios --flavor ${FLAVOR} --target lib/main_${TARGET}.dart ​--export-options-plist=/Users/builder/export_options.plist

    - &patch_android
      name: 🤖 Android PATCH Build
      script: |
        shorebird patch android --flavor ${FLAVOR} --target lib/main_${TARGET}.dart

    - &patch_ios
      name: 🍎 iOS PATCH Build
      script: |
        shorebird patch ios --flavor ${FLAVOR} --target lib/main_${TARGET}.dart ​--export-options-plist=/Users/builder/export_options.plist

workflows:
  release-list-production:
    name: Release List Production

    environment:
      vars:
        TARGET: prod
        FLAVOR: prod
        BUNDLE: com.example.list
      groups:
        - list
        - shorebird
      flutter: 3.22.0
      xcode: 15.0.1
      cocoapods: default
      java: 17
    max_build_duration: 60

    triggering:
      events:
        - pull_request
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    when:
      condition: not event.tag

    scripts:
      - *create_env_files
      - *set_up_local_properties
      - *run_build_runner
      - *shorebird_install
      - *build_android

    artifacts:
      - build/**/outputs/*apk/**/*.apk
      - build/**/outputs/*bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - andikamufc@gmail.com
        notify:
          success: true
          failure: false

  patch-list-production:
    name: Patch List Production
    max_build_duration: 60
    triggering:
      events:
        - push
        - tag
      branch_patterns:      
        - pattern: 'main'
      tag_patterns:
        - pattern: 'hotfix'
          include: true
      cancel_previous_builds: true
    environment:
      java: 17
      groups:
        - list
        - shorebird
      flutter: 3.22.0
      xcode: 15.0.1
      cocoapods: default
      vars:
        TARGET: prod
        FLAVOR: prod
        BUNDLE: com.example.list
    scripts:
      - *create_env_files
      - *set_up_local_properties
      - *run_build_runner
      - *shorebird_install
      - *patch_android
      # - *patch_ios
    artifacts:
      - build/**/outputs/*apk/**/*.apk
      - build/**/outputs/*bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - andikamufc@email.com
        notify:
          success: true
          failure: false