name: list
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  custom_refresh_indicator: ^3.1.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  restart_app: ^1.2.1
  shorebird_code_push: ^1.1.3
  svg_flutter: ^0.0.1
  upgrader: ^10.3.0

dev_dependencies:
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - shorebird.yaml
    - assets/
  uses-material-design: true
